services:
  client:
    build:
      context: ./client
      dockerfile: client.Dockerfile
    # volumes:
    # - ./client:/app/client
    # - ./client/node_modules:/app/client/node_modules
    ports:
      - "3000:5173"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: server.Dockerfile
    # volumes:
    #   - ./server:/app/server
    #   - ./server/node_modules:/app/server/node_modules
    ports:
      - "8000:8000"
  # depends_on:
  #   - mysql
#   mysql:
#     image: mysql:8.4
#     volumes:
#       - mysql_data:/var/lib/mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: mydatabase
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     ports:
#       - "3306:3306"
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       interval: 30s
#       timeout: 10s
#       retries: 5

# volumes:
#   mysql_data:
