services:
  client:
    image: node:20
    volumes:
      - ./client:/app/client
    ports:
      - "3000:5173"
    working_dir: /app/client
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - server

  server:
    image: node:20
    volumes:
      - ./server:/app/server
    ports:
      - "8000:8000"
    working_dir: /app/server
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
