services:
  client:
    image: node:20
    working_dir: /app/client
    volumes:
      - ./client:/app/client
      - ./client/node_modules:/app/client/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "3000:5173"

  server:
    image: node:20
    working_dir: /app/server
    volumes:
      - ./server:/app/server
      - ./server/node_modules:/app/server/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
