services:
  client:
    build:
      context: ./client
      dockerfile: client.Dockerfile
    volumes:
      - ./client:/app/client
      - ./client/node_modules:/app/client/node_modules
    ports:
      - "3000:5173"

  server:
    build:
      context: ./server
      dockerfile: server.Dockerfile
    volumes:
      - ./server:/app/server
      - ./server/node_modules:/app/server/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
