x-variables:
  NODE_VERSION: &NODE_VERSION 20

services:
  client:
    build:
      context: ./client
      dockerfile: client.Dockerfile
      args:
        NODE_VERSION: *NODE_VERSION
    volumes:
      - client_node_modules:/app/client/node_modules
      - ./client:/app/client
    ports:
      - "3000:5173"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: server.Dockerfile
      args:
        NODE_VERSION: *NODE_VERSION
    volumes:
      - server_node_modules:/app/server/node_modules
      - ./server:/app/server
    ports:
      - "8000:8000"

  # depends_on:
  #   - mysql
#   mysql:
#     image: mysql:8.4
#     volumes:
#       - mysql_data:/var/lib/mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: mydatabase
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     ports:
#       - "3306:3306"
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       interval: 30s
#       timeout: 10s
#       retries: 5

volumes:
  client_node_modules:
  server_node_modules:
#   mysql_data:
